import { config, validateConfig } from './config.js';
import { Store } from './store.js';
import { RunService } from './run-service.js';
import { buildApi } from './api.js';
import { openSecret } from './security.js';
import { setRepositoryToken } from './github.js';
validateConfig();
const store = await Store.open(config.dataDir, config.databaseUrl);
const storedGitHubToken = await store.secret('github-token');
if (storedGitHubToken) setRepositoryToken(openSecret(storedGitHubToken, config.sessionSecret));
const runs = new RunService(store);
const app = await buildApi(store, runs);
runs.start();
const shutdown = async () => {
  runs.stop();
  await app.close();
  await store.close();
  process.exit(0);
};
process.on('SIGTERM', () => void shutdown());
process.on('SIGINT', () => void shutdown());
await app.listen({ host: config.host, port: config.port });
