import type { CheckCommand } from '../../../shared/types.js';
const check = (
  id: string,
  kind: CheckCommand['kind'],
  argv: string[],
  report: CheckCommand['report'] = 'exit',
  reportPath = '',
): CheckCommand => ({
  id,
  label: id.replace(/-/g, ' '),
  kind,
  argv,
  report,
  reportPath,
  required: true,
  timeoutSeconds: 600,
});
export const profiles: Record<string, CheckCommand[]> = {
  typescript: [
    check('install', 'setup', ['npm', 'ci']),
    check('build', 'build', ['npm', 'run', 'build']),
    check('lint', 'lint', ['npm', 'run', 'lint']),
    check('typecheck', 'types', ['npm', 'run', 'typecheck']),
    check(
      'unit',
      'unit',
      ['npm', 'exec', '--', 'vitest', 'run', '--reporter=json', '--outputFile=.reports/unit.json'],
      'vitest',
      '.reports/unit.json',
    ),
    check('e2e', 'e2e', ['npm', 'run', 'test:e2e', '--', '--reporter=json'], 'playwright', '.reports/e2e.json'),
    check('secrets', 'security', ['@sdlc/security', 'secrets'], 'gitleaks', '.reports/secrets.json'),
    check('sast', 'security', ['@sdlc/security', 'sast'], 'semgrep', '.reports/sast.json'),
    check('dependencies', 'security', ['npm', 'audit', '--json'], 'npm-audit', '.reports/audit.json'),
  ],
  python: [
    check('install', 'setup', ['uv', 'sync', '--frozen']),
    check('build', 'build', ['uv', 'build']),
    check('lint', 'lint', ['uv', 'run', '--no-sync', 'ruff', 'check', '.']),
    check('typecheck', 'types', ['uv', 'run', '--no-sync', 'mypy', '.']),
    check(
      'unit',
      'unit',
      ['uv', 'run', '--no-sync', 'pytest', 'tests/unit', '--junitxml=.reports/unit.xml'],
      'junit',
      '.reports/unit.xml',
    ),
    check(
      'integration',
      'integration',
      ['uv', 'run', '--no-sync', 'pytest', 'tests/integration', '--junitxml=.reports/integration.xml'],
      'junit',
      '.reports/integration.xml',
    ),
    check('secrets', 'security', ['@sdlc/security', 'secrets'], 'gitleaks', '.reports/secrets.json'),
    check('sast', 'security', ['@sdlc/security', 'sast'], 'semgrep', '.reports/sast.json'),
    check(
      'dependencies',
      'security',
      ['uv', 'run', '--no-sync', 'pip-audit', '--format=json'],
      'pip-audit',
      '.reports/audit.json',
    ),
  ],
};
